/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package modelo;

/**
 *
 * @author ruby
 */
public class TaqueriaRU extends javax.swing.JFrame {

    /**
     * Creates new form TaqueriaRU
     */
    public TaqueriaRU() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cebolla = new javax.swing.JCheckBox();
        cilantro = new javax.swing.JCheckBox();
        pina = new javax.swing.JCheckBox();
        queso = new javax.swing.JCheckBox();
        tomarOrden = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("¡¡¡QUE LE PONEMOS A TUS TAQUITOS????");

        cebolla.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        cebolla.setText("CEBOLLA");

        cilantro.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        cilantro.setText("CILANTRO");
        cilantro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cilantroActionPerformed(evt);
            }
        });

        pina.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        pina.setText("PIÑA");
        pina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinaActionPerformed(evt);
            }
        });

        queso.setFont(new java.awt.Font("Book Antiqua", 0, 12)); // NOI18N
        queso.setText("QUESO");

        tomarOrden.setFont(new java.awt.Font("Algerian", 0, 12)); // NOI18N
        tomarOrden.setText("TOMAR ORDEN");
        tomarOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tomarOrdenActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel2.setText("TUS TACOS VAN............");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(cilantro)
                            .addComponent(cebolla)
                            .addComponent(pina)
                            .addComponent(queso)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(tomarOrden))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addComponent(cebolla)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cilantro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pina)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(queso)
                .addGap(18, 18, 18)
                .addComponent(tomarOrden)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cilantroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cilantroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cilantroActionPerformed

    private void pinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pinaActionPerformed

    private void tomarOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tomarOrdenActionPerformed
    String orden ="";
    if (cebolla.isSelected()){
        orden = orden + "con cebolla\n";
        jTextArea1.setText(orden);
    }    if (cilantro.isSelected()){
        orden = orden + "con cilantro\n";
        jTextArea1.setText(orden);
    }    if (pina.isSelected()){
        orden = orden + "con piña\n";
        jTextArea1.setText(orden);
    }     if (queso.isSelected()){
        orden = orden + "con queso\n";
        jTextArea1.setText(orden);
    } 
    }//GEN-LAST:event_tomarOrdenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaqueriaRU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaqueriaRU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaqueriaRU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaqueriaRU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TaqueriaRU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cebolla;
    private javax.swing.JCheckBox cilantro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JCheckBox pina;
    private javax.swing.JCheckBox queso;
    private javax.swing.JButton tomarOrden;
    // End of variables declaration//GEN-END:variables
}
